services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:${APP_INTERNAL_PORT:-6669}"
    environment:
      # Set node environment, default to development
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${APP_INTERNAL_PORT:-6669}
      - HOST=0.0.0.0
      # Database connection variables
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${DB_INTERNAL_PORT:-5432}/${POSTGRES_DB:-badges_dev}
      - DB_HOST=db
      - DB_PORT=${DB_INTERNAL_PORT:-5432}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-badges_dev}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - ./certs:/app/certs:delegated
      # Startup scripts are in /docker-scripts directory which is outside the /app mount point
    networks:
      - bun-badges-network
    restart: unless-stopped
    # The Dockerfile.dev entrypoint will handle installation and startup

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      # Expose DB port for dev tools
      - "${DB_PORT:-5432}:${DB_INTERNAL_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bun-badges-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules:

networks:
  bun-badges-network:
    driver: bridge