FROM oven/bun:1.0-alpine

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache bash postgresql-client

# Copy package files for dependency installation
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install

# Copy the rest of the application
COPY . .

# Set the command to run tests by default
CMD ["bun", "test:e2e:vitest"] 