version: '3.8'

services:
  api:
    image: oven/bun:1
    container_name: bun-badges-api-dev-light
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DOCKER_CONTAINER: 'true'
      SKIP_CANVAS: 'true'
    ports:
      - "${PORT:-7777}:7777"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "bun install --no-optional &&
             bun run dev"
    networks:
      - bun-badges-network

  db:
    image: postgres:15
    container_name: bun-badges-db-light
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - postgres_data_light:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bun-badges-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bun-badges-pgadmin-light
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data_light:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - bun-badges-network

volumes:
  postgres_data_light:
  pgadmin_data_light:

networks:
  bun-badges-network:
    driver: bridge