services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      # Set node environment, default to development
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - ./certs:/app/certs:delegated
      # Startup scripts are in /docker-scripts directory which is outside the /app mount point
    networks:
      - bun-badges-network
    restart: unless-stopped
    # The Dockerfile.dev entrypoint will handle installation and startup

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      # Expose DB port for dev tools, default to 5433
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bun-badges-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules:

networks:
  bun-badges-network:
    driver: bridge 